// Code generated by MockGen. DO NOT EDIT.
// Source: active_evse_location_usecase.go
//
// Generated by this command:
//
//	mockgen -source=active_evse_location_usecase.go -destination=./mock/mock_usecase.go
//

// Package mock_usecase is a generated GoMock package.
package mock

import (
	context "context"
	domain "go-challenge/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIActiveEVSELocationUseCase is a mock of IActiveEVSELocationUseCase interface.
type MockIActiveEVSELocationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIActiveEVSELocationUseCaseMockRecorder
}

// MockIActiveEVSELocationUseCaseMockRecorder is the mock recorder for MockIActiveEVSELocationUseCase.
type MockIActiveEVSELocationUseCaseMockRecorder struct {
	mock *MockIActiveEVSELocationUseCase
}

// NewMockIActiveEVSELocationUseCase creates a new mock instance.
func NewMockIActiveEVSELocationUseCase(ctrl *gomock.Controller) *MockIActiveEVSELocationUseCase {
	mock := &MockIActiveEVSELocationUseCase{ctrl: ctrl}
	mock.recorder = &MockIActiveEVSELocationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIActiveEVSELocationUseCase) EXPECT() *MockIActiveEVSELocationUseCaseMockRecorder {
	return m.recorder
}

// FindLocationsWithActiveEVSE mocks base method.
func (m *MockIActiveEVSELocationUseCase) FindLocationsWithActiveEVSE(ctx context.Context, latitude, longitude float64, radius int) ([]domain.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLocationsWithActiveEVSE", ctx, latitude, longitude, radius)
	ret0, _ := ret[0].([]domain.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLocationsWithActiveEVSE indicates an expected call of FindLocationsWithActiveEVSE.
func (mr *MockIActiveEVSELocationUseCaseMockRecorder) FindLocationsWithActiveEVSE(ctx, latitude, longitude, radius any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLocationsWithActiveEVSE", reflect.TypeOf((*MockIActiveEVSELocationUseCase)(nil).FindLocationsWithActiveEVSE), ctx, latitude, longitude, radius)
}
