// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Evse struct {
	ID         int32  `json:"id"`
	LocationID int32  `json:"location_id"`
	Uid        string `json:"uid"`
	Status     int32  `json:"status"`
}

type Location struct {
	ID          int32          `json:"id"`
	Name        sql.NullString `json:"name"`
	Address     string         `json:"address"`
	Latitude    string         `json:"latitude"`
	Longitude   string         `json:"longitude"`
	LastUpdated time.Time      `json:"last_updated"`
}
