// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"time"
)

const getAllEVSEs = `-- name: GetAllEVSEs :many
SELECT id, location_id, uid, status
FROM evses
`

func (q *Queries) GetAllEVSEs(ctx context.Context) ([]Evse, error) {
	rows, err := q.db.QueryContext(ctx, getAllEVSEs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evse
	for rows.Next() {
		var i Evse
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Uid,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLocations = `-- name: GetAllLocations :many
SELECT id, name, address, latitude, longitude, last_updated
FROM locations
`

func (q *Queries) GetAllLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, getAllLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEVSEsByLocationID = `-- name: GetEVSEsByLocationID :many
SELECT id, location_id, uid, status
FROM evses
WHERE location_id = ?
`

func (q *Queries) GetEVSEsByLocationID(ctx context.Context, locationID int32) ([]Evse, error) {
	rows, err := q.db.QueryContext(ctx, getEVSEsByLocationID, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evse
	for rows.Next() {
		var i Evse
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Uid,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationsByDateFrom = `-- name: GetLocationsByDateFrom :many
SELECT id, name, address, latitude, longitude, last_updated
FROM locations
WHERE last_updated >= ?
`

func (q *Queries) GetLocationsByDateFrom(ctx context.Context, lastUpdated time.Time) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, getLocationsByDateFrom, lastUpdated)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationsByDateRange = `-- name: GetLocationsByDateRange :many
SELECT id, name, address, latitude, longitude, last_updated
FROM locations
WHERE last_updated >= ? AND last_updated < ?
`

type GetLocationsByDateRangeParams struct {
	LastUpdated   time.Time `json:"last_updated"`
	LastUpdated_2 time.Time `json:"last_updated_2"`
}

func (q *Queries) GetLocationsByDateRange(ctx context.Context, arg GetLocationsByDateRangeParams) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, getLocationsByDateRange, arg.LastUpdated, arg.LastUpdated_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationsByDateTo = `-- name: GetLocationsByDateTo :many
SELECT id, name, address, latitude, longitude, last_updated
FROM locations
WHERE last_updated < ?
`

func (q *Queries) GetLocationsByDateTo(ctx context.Context, lastUpdated time.Time) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, getLocationsByDateTo, lastUpdated)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
